name: Python package

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel aiohttp  # Needed for building the package

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel  # This creates the source and wheel distributions

    - name: Upload to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*  # This uploads the distributions to PyPI